name: driveu_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  location: ^7.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vehicle_models_cleaned.json
    - assets/us_institutions.json
