name: driveu_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  http: ^1.2.2
  image_picker: ^1.1.2
  dio: ^4.0.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  location: ^7.0.1
  provider: ^6.1.2
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  firebase_messaging: ^15.2.2
  webview_flutter: ^4.10.0
  duration_picker: ^1.2.0
  flutter_colorpicker: ^0.6.0
  flutter_local_notifications: ^18.0.1
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - e.env
    - assets/images/
    - assets/vehicle_models_cleaned.json
    - assets/us_institutions.json
    - assets/paypal_login.html
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700